version: "3.4"

networks:
  default:
    external:
      name: crossbeam-unified  # created by razor

services:

  neo4j:
    image: neo4j:3.5.3
    environment:
      - NEO4J_AUTH=none
      - NEO4J_HOST=0.0.0.0
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - neo4j:/data

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
      args:
        UID: ${UID}
        USER: xbeamer
    volumes:
      - .:/app
      - ~/.m2:/home/xbeamer/.m2
    links:
      - neo4j:localgraph
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - neo4j

volumes:
  neo4j:
